### ISSUE TITLE
Not working with 11.3.2?

### ISSUE THREAD

**Issue by technochitlin** [CoryWBoris/AbletonAutoColor#1]
Or is it just me? Had it working on 11.2.11 but after the update I cannot load the device

**Comment by CoryWBoris** [comment]
Hello,

Sorry to hear that it has been having some difficulties working! I can
confirm the current github script as it is now works without any issues on
my setup. Im using the beta version of 11.3(b5) so it should work with any
earlier version of Live 11 too. Sometimes when live updates it refreshes
the control surfaces to defaults. Did you reselect it in preferences if
that is the case? And if not, what is the error, just no functioning after
name change? I truly only troubleshooted this on a Mac, so I can help you
better if you use a Mac. Let me know either way!

Best,
Cory

**Comment by technochitlin** [comment]
Cory-

Thanks for the swift reply. When I first set it up in Live 11.2.11, I created a folder E:\Ableton\User Library\Remote Scripts and put your files in it. Everything worked fine, colors changed as they should have. I updated to 11.3.2 and, though the folder and the files are still there, I cannot select or find the ColorChanger control surface. Any idea what might have happened?

 �

Cheers,

jw

 �

**Comment by CoryWBoris** [comment]
Hey jw,

Unfortunately it seems i cant test this on 11.3.2 as i dont believe it is
available for me yet. Such a shame! I wish i could help more. I can already
hear myself gulping at the notion that i will deal with the same issue when
i update *sigh*

-C

**Comment by CoryWBoris** [comment]
Hey so i digged a little bit into this... referring to the ableton website,
it seems to point to a different location than the one you gave for remote
scripts. Ableton says: "\Users\[username]\Documents\Ableton\User Library"
for the location of the remote scripts folder. Let me know if this makes
any difference!

-C

**Comment by technochitlin** [comment]
I don’t know about the Mac version, but Live in Windows lets me put the Library and Factory Pack folders anywhere I want to-



 �

And that is where I originally installed ColorChanger- and it worked, before I updated Live to 11.3.2

 �

Cheers,

jw

**Comment by CoryWBoris** [comment]
So while Ableton may have allowed that script to run in the folder you said
it was in, it wasnt the correct directory for this class of user scripts.
This took me awhile to get as there are three different scripts Ableton
allows for control surfaces, and they all behave differently.

First there are user remote scripts which are text files used for auxillary
assignment of numerous optional mapping possibilities for a midi
controller, only entered by the user as an option.

Then there are Remote Scripts which allow the user to write python directly
at their leisure to do anything as long as you use the libraries ableton's
virtual python environment allows.

Lastly there are Midi Remote scripts, these are written by Ableton and have
a special signature which makes it difficult to mess with their
functionality without screwing up your midi controller as these scripts are
what let your controller ultimately have its mappings correct on load
without having to assign basic mappings.

The fact that the scripts i wrote worked in the midi remote scripts folder
is most likely a bug that was sealed, as that functionality shouldnt have
been able to happen since those scripts in that midi remote scripts folder
need a very specific code base.

Trust me, i know we havent met, but the folder i recommended on the github
is the de facto best location for the scripts. Ableton most likely fixed a
bug that let you previously operate from the incorrect directory. If you
move the scripts as I have them written into the Remote Scripts folder and
the control surface doesnt work, i would be very suprised.

Best,
Cory

**Comment by technochitlin** [comment]
Okay, I can see that. I created the folder in the exact location specified in the Readme.md file. Still no joy- Live cannot find the device. Is there some sort of init file that needs to be edited, possibly?

 �

Cheers,

jw

 �

**Comment by CoryWBoris** [comment]
The __init__ file which i included in the repo absolutely needs to be
included in the same directory as the ColorChanger.py file, so it should be
in the following order overall, and the init file does not need any editing:

Remote Scripts (Folder)
    -Color Changer (Folder)
          -__init__.py
          -ColorChanger.py

Best,
Cory

**Comment by CoryWBoris** [comment]
Also Live needs to restart for changes to reflect if you modify the file
structure at any point. Let me know if it doesnt work after having the
exact file structure specified in the Readme

Best,
Cory
